

main_matlab_check_energy_ratio_false_positive_rate('ambient_t3');
main_matlab_check_energy_ratio_false_positive_rate('ambient_t5');
main_matlab_check_energy_ratio_false_positive_rate('ambient_t6');

main_matlab_check_energy_ratio_false_positive_rate('bodysound_t4');
main_matlab_check_energy_ratio_false_positive_rate('bodysound_t7');

main_matlab_check_energy_ratio_false_positive_rate('classical_t1');
main_matlab_check_energy_ratio_false_positive_rate('classical_t2');
main_matlab_check_energy_ratio_false_positive_rate('classical_t3');
main_matlab_check_energy_ratio_false_positive_rate('classical_t4');

main_matlab_check_energy_ratio_false_positive_rate('pop_t1');
main_matlab_check_energy_ratio_false_positive_rate('pop_t2');
main_matlab_check_energy_ratio_false_positive_rate('pop_t3');
main_matlab_check_energy_ratio_false_positive_rate('pop_t4');
main_matlab_check_energy_ratio_false_positive_rate('pop_t5');
main_matlab_check_energy_ratio_false_positive_rate('pop_t6');

main_matlab_check_energy_ratio_false_positive_rate('tv_t1');
main_matlab_check_energy_ratio_false_positive_rate('tv_t2');
main_matlab_check_energy_ratio_false_positive_rate('tv_t3');
main_matlab_check_energy_ratio_false_positive_rate('tv_t4');
main_matlab_check_energy_ratio_false_positive_rate('tv_t5');



